# Author Remo Mattei
# Email: rm@rm.ht
---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
      api_version: "{{ api_version }}"
      username: "{{ username }}"
      password: "{{ password }}"
      controller: "{{ controllers.0.mgmt_ip }}"
  tasks:
    - name: Deploy Avi Controllers
      community.vmware.vmware_deploy_ovf:
        hostname: "{{vcenter.vcenter_url}}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        datacenter: "{{ vcenter.datacenter }}"
        cluster: "{{ cluster }}"
        datastore: "{{ datacenter_datastore }}"
        validate_certs: false
        name: "{{ item.vm_name }}"
        networks: '{u"Management":u"{{ mgmt_network }}"}'
        ovf: '{{ ova_path }}'
        folder: '{{ vcenter.datacenter + "/vm/" + vcenter_folder }}'
        properties: '{ u"avi.mgmt-ip.CONTROLLER":u"{{ item.mgmt_ip }}", u"avi.mgmt-mask.CONTROLLER":u"{{ item.mgmt_mask }}", u"avi.default-gw.CONTROLLER":u"{{ item.default_gw }}"}'
        power_on: true
        allow_duplicates: false
      loop: "{{ controllers }}"
      register: _ctl_0
      async: 6000
      poll: 0
    - name: Wait for My long running task to finish
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: _jobs_ctl_0
      retries: 3000
      delay: 10
      until: _jobs_ctl_0.finished
      loop: "{{ _ctl_0.results }}"
