---
- hosts: localhost
  connection: local
  roles:
    - role: avinetworks.avicontroller_vmware
    - role: avinetworks.avisdk
    - role: avinetworks.aviconfig
  gather_facts: False
  tasks:
    - name: Wait for Controller be ready
      uri:
        validate_certs: False
        url: "http://{{ controllers.0.mgmt_ip }}/"
        method: GET
        status_code: 200,302,301,503
      register: statusCode_output
      until: statusCode_output.status == 200
      retries: 120
      delay: 60
    - name: Wait for controller 2 be ready
      uri:
        validate_certs: False
        url: "http://{{ controllers.1.mgmt_ip }}/"
        method: GET
        status_code: 200,302,301,503
      register: statusCode_output
      until: statusCode_output.status == 200
      retries: 120
      delay: 60
      tags:
        - second_ctl
    - name: Wait for controller 3 be ready
      uri:
        validate_certs: False
        url: "http://{{ controllers.2.mgmt_ip }}/"
        method: GET
        status_code: 200,302,301,503
      register: statusCode_output
      until: statusCode_output.status == 200
      retries: 120
      delay: 60
      tags:
        - third_ctl
    - name: Set admin password
      avi_useraccount:
        avi_credentials: '{{ avi_credentials }}'
        old_password: '{{ old_password }}'
        api_version: '{{ api_version }}'
        controller: '{{ controllers.0.mgmt_ip }}'
      tags:
        - passwordavi
    - name: Basic Controller Config
      avi_systemconfiguration:
        controller: '{{ controllers.0.mgmt_ip }}'
        username: '{{ username }}'
        password: '{{ password }}'
        api_version: '{{ api_version }}'
        email_configuration:
          smtp_type: SMTP_LOCAL_HOST
          from_email: '{{ avi_email }}'
        global_tenant_config:
          se_in_provider_context: True
          tenant_access_to_provider_se: True
          tenant_vrf: False
        dns_configuration:
          search_domain: '{{ search_domains }}'
          server_list:
            - type: V4
              addr: '{{ dns_server01 }}'
            - type: V4
              addr: '{{ dns_server02 }}'
        portal_configuration:
          use_uuid_from_input: False
          redirect_to_https: True
          disable_remote_cli_shell: False
          enable_clickjacking_protection: True
          enable_http: True
          enable_https: True
          password_strength_check: True
          allow_basic_authentication: False
          disable_swagger: False
        ntp_configuration:
          ntp_servers:
            - server:
                type: DNS
                addr: "{{ ntp_server01 }}"
            - server:
                type: DNS
                addr: "{{ ntp_server02 }}"
        default_license_tier: ENTERPRISE_18
        welcome_workflow_complete: True
        linux_configuration:
          motd: "{{ motd_welcome }}"
          banner: "{{ banner_txt }}"
      tags:
        - controllerconfig
