---
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Define Cloud Connector configuration
      set_fact:
        no_log: True
        avi_config_cloud:
          avi_cloud_discovery_wait: "{{ vcenter.cloud_discovery_time }}"
          cloud:
            - vtype: CLOUD_VCENTER
              license_tier: ENTERPRISE_18
              name: "{{ vcenter.AviCloudName }}"
              vcenter_configuration:
                username: "{{ vcenter.username }}"
                datacenter: "{{ vcenter.datacenter }}"
                management_network: "/api/vimgrnwruntime/?name={{ vcenter.network_mgmt }}"
                management_ip_subnet:
                  mask: "{{ vcenter.network_subnet_mask }}"
                  ip_addr:
                    type: V4
                    addr: "{{ vcenter.network_subnet }}"
                privilege: WRITE_ACCESS
                vcenter_url: "{{ vcenter.vcenter_url }}"
                password: "{{ vcenter.password }}"
              enable_vip_static_routes: True
              prefer_static_routes: True
              license_type: LIC_CORES

    - name: Discover Cloud Subnets
      no_log: True
      import_role:
        name: avinetworks.aviconfig
      vars:
        avi_config: "{{ avi_config_cloud }}"

    - name: Setup Cloud Connector
      no_log: True
      import_role:
        name: avinetworks.aviconfig
      vars:
        avi_config: "{{ avi_config_cloud }}"
