# Author Remo Mattei
# Email: rm@rm.ht
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Configure SE Group
      no_log: True
      import_role:
        name: avinetworks.aviconfig
      vars:
        avi_config:
          serviceenginegroup:
            - name: "{{ vcenter.AviCloudName }}"
              cloud_ref: "{{'/api/cloud?name='+ vcenter.AviCloudName }}"
              se_name_prefix: "{{ vcenter.se_prefix }}"
              placement_mode: PLACEMENT_MODE_AUTO
              ha_mode: HA_MODE_SHARED_PAIR 
              algo: PLACEMENT_ALGO_PACKED
              vcpus_per_se: 6
              cpu_reserve: True
              memory_per_se: 12288
              mem_reserve: True
              disk_per_se: 64
              min_se: 4
              max_se: 6
              buffer_se: 2
              min_scaleout_per_vs: 4
              max_scaleout_per_vs: 6
              dedicated_dispatcher_core: True
              se_deprovision_delay: 0
              license_type: LIC_CORES
              vcenter_clusters:
                include: True
                cluster_refs:
                  - "{{ '/api/vimgrhostruntime/?name=' + cluster }}"
              vcenter_datastores_include: True
              vcenter_datastore_mode: VCENTER_DATASTORE_SHARED
              vcenter_datastores:
                  - datastore_name: "{{ datacenter_datastore }}"
              vcenter_folder: "{{ vcenter_folder }}"
            - name: "{{ vcenter.AviCloudName }}-AA"
              cloud_ref: "{{'/api/cloud?name='+ vcenter.AviCloudName }}"
              se_name_prefix: "{{ vcenter.se_prefix }}"
              placement_mode: PLACEMENT_MODE_AUTO
              ha_mode: HA_MODE_SHARED_PAIR
              algo: PLACEMENT_ALGO_PACKED
              realtime_se_metrics:
                enabled: True
                duration: 10
              vcpus_per_se: 6
              cpu_reserve: True
              memory_per_se: 12288
              mem_reserve: True
              disk_per_se: 64
              min_se: 4
              max_se: 6
              buffer_se: 2
              min_scaleout_per_vs: 4
              max_scaleout_per_vs: 6
              dedicated_dispatcher_core: True
              se_deprovision_delay: 5
              license_type: LIC_CORES
              vcenter_folder: "{{ vcenter_folder }}"
          backupconfiguration:
            - name: Backup-Configuration
              backup_passphrase: '{{ backup_passphrase }}'
              save_local: True
