# Author Remo Mattei
# Email: rm@rm.ht
---
- hosts: localhost
  gather_facts: no
  connection: local
  collections:
    - vmware.alb
  tasks:
    - name: "Configure SE Groups"
      vmware.alb.avi_serviceenginegroup:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ vcenter.AviCloudName }}-Default"
        cloud_ref: "{{'/api/cloud?name='+ vcenter.AviCloudName }}"
        vcenter_folder: "{{ vcenter_folder }}"
        se_name_prefix: "{{ vcenter.se_prefix }}"
        max_vs_per_se: "{{ max_se_number | default(omit) }}"
        max_se: "{{ max_se | default(omit) }}"
        min_scaleout_per_vs: "{{ min_scaleout_per_se | default(1) }}"
        vcpus_per_se: "{{ vcpu_number | default(1) }}"
        memory_per_se: "{{ memory_per_se | default(2048) }}"
        mem_reserve: True
        disk_per_se: "{{ disk_per_se | default(15) }}"
        vcenter_hosts: "{{ vcenter_hosts | default(omit) }}"
        placement_mode: PLACEMENT_MODE_AUTO
        vcenter_datastore_mode: VCENTER_DATASTORE_SHARED
        vcenter_datastores_include: True
        vcenter_clusters:
                include: True
                cluster_refs:
                  - "{{ '/api/vimgrhostruntime/?name=' + cluster }}"
        vcenter_datastores:
                  - datastore_name: "{{ datacenter_datastore }}"
        ha_mode: "HA_MODE_SHARED"
        algo: PLACEMENT_ALGO_PACKED
        buffer_se: "{{ buffer_for_se | default(omit) }}"
        se_deprovision_delay: "{{ se_deletion | default(omit) }}"
    - name: "Configure SE Groups AA"
      vmware.alb.avi_serviceenginegroup:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ vcenter.AviCloudName }}-AA"
        cloud_ref: "{{'/api/cloud?name='+ vcenter.AviCloudName }}"
        vcenter_folder: "{{ vcenter_folder }}"
        se_name_prefix: "{{ vcenter.se_prefix }}"
        min_scaleout_per_vs: "{{ aa_min_scaleout_per_se | default(1) }}"
        max_scaleout_per_vs: "{{ aa_max_scaleout_per_se }}"
        max_vs_per_se: "{{ aa_max_se_number | default(omit) }}"
        max_se: "{{ aa.max_se | default(omit) }}"
        vcpus_per_se: "{{ aa_vcpu_number | default(1) }}"
        memory_per_se: "{{ aa_memory_per_se | default(2048) }}"
        mem_reserve: True
        disk_per_se: "{{ aa_disk_per_se | default(15) }}"
        vcenter_hosts: "{{ vcenter_hosts | default(omit) }}"
        placement_mode: PLACEMENT_MODE_AUTO
        vcenter_datastore_mode: VCENTER_DATASTORE_SHARED
        vcenter_datastores_include: True
        vcenter_clusters:
                include: True
                cluster_refs:
                  - "{{ '/api/vimgrhostruntime/?name=' + cluster }}"
        vcenter_datastores:
                  - datastore_name: "{{ datacenter_datastore }}"
        ha_mode: HA_MODE_SHARED_PAIR
        algo: PLACEMENT_ALGO_PACKED
        buffer_se: "{{ aa_buffer_for_se | default(omit) }}"
        se_deprovision_delay: "{{ aa_se_deletion | default(omit) }}"
      tags:
        - AA
