---
- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Get Facts Avi Cluster Config
      no_log: False
      import_role:
        name: avinetworks.aviconfig
      vars:
        avi_credentials:
          api_version: "{{ api_version }}"
          username: "{{ username }}"
          password: "{{ password }}"
          controller: "{{ controllers.0.mgmt_ip }}"
        avi_config_cluster:
          cluster:
            - nodes:
                - ip:
                    type: V4
                    addr: "{{ controllers.0.mgmt_ip }}"
                - ip:
                    type: V4
                    addr: "{{ controllers.1.mgmt_ip }}"
                - ip:
                    type: V4
                    addr: "{{ controllers.2.mgmt_ip }}"
              name: '{{ cluster_name }}'
              virtual_ip:
                type: V4
                addr: "{{ cluster_IP }}"
    - name: Setup Avi Cluster Nodes and  IPs
      import_role:
        name: avinetworks.aviconfig
      vars:
        avi_config: "{{ avi_config_cluster }}"
