# Author Remo Mattei
# Email: rm@rm.ht
---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Generate Private key.
      openssl_privatekey:
        path: "{{ horizon_path }}/{{ horizon_key }}"
    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "{{ horizon_path }}/{{ horizon_csr }}"
        privatekey_path: "{{ horizon_path }}/{{ horizon_key }}"
        country_name: "{{ country }}"
        organization_name: "{{ organization }}"
        email_address: "{{ email }}"
        common_name: "{{ common_name }}"
      tags:
        - create_csr
    - name: Generate a Self Signed OpenSSL certificate.
      openssl_certificate:
        path: "{{ horizon_path }}/{{ horizon_fullchain }}"
        privatekey_path: "{{ horizon_path }}/{{ horizon_key }}"
        csr_path: "{{ horizon_path }}/{{ horizon_csr }}" 
        provider: selfsigned
    - name: Configure SE Group
      no_log: false
      import_role:
        name: avinetworks.aviconfig
      vars:
        avi_config:
          sslprofile:
            - name: Horizon-avi-ssl
              tenant: admin
              accepted_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA
              accepted_versions:
              - type: SSL_VERSION_TLS1
              - type: SSL_VERSION_TLS1_1
              - type: SSL_VERSION_TLS1_2
          sslkeyandcertificate:
            - name: Horizon_SSL_Cert
              tenant: admin
              certificate:
                self_signed: true
                certificate: "{{ lookup('file', '/opt/avi/ansi-controller/certs/{{ horizon_fullchain }}' )}}"
              key: "{{ lookup('file', '/opt/avi/ansi-controller/certs/{{ horizon_key }}' )}}"
